name: deepchem-da
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - rdkit
  - scikit-learn
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pyg
  - pip
